"""Add Group table

Revision ID: 1c2a40014f18
Revises: e74ec8163305
Create Date: 2025-01-25 03:26:19.391760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1c2a40014f18'
down_revision: Union[str, None] = 'e74ec8163305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('departments_ibfk_2', 'departments', type_='foreignkey')
    op.drop_column('departments', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('group_id', mysql.VARCHAR(length=60), nullable=True))
    op.create_foreign_key('departments_ibfk_2', 'departments', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
