"""Add attendance table

Revision ID: 3a065e8ef6c7
Revises: df74f2701751
Create Date: 2025-01-24 16:03:47.347276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a065e8ef6c7'
down_revision: Union[str, None] = 'df74f2701751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('attendance', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('attendance', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'date')
    op.drop_column('attendance', 'remarks')
    op.drop_column('attendance', 'status')
    # ### end Alembic commands ###
