"""Upgrade department with leader_id

Revision ID: 3cccc72da3ca
Revises: 3927448c1ceb
Create Date: 2025-01-25 00:45:18.780249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3cccc72da3ca'
down_revision: Union[str, None] = '3927448c1ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('leader_id', sa.String(length=60), nullable=False))
    op.drop_constraint('departments_ibfk_1', 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'members', ['leader_id'], ['id'])
    op.drop_column('departments', 'head')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('head', mysql.VARCHAR(length=60), nullable=False))
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key('departments_ibfk_1', 'departments', 'members', ['head'], ['id'])
    op.drop_column('departments', 'leader_id')
    # ### end Alembic commands ###
