"""Creates financial_records table

Revision ID: 3f2cfd419e9f
Revises: fb3d3cfd1144
Create Date: 2025-01-24 13:02:10.575666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3f2cfd419e9f'
down_revision: Union[str, None] = 'fb3d3cfd1144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('events', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('events', sa.Column('start_time', sa.Time(), nullable=False))
    op.add_column('events', sa.Column('end_time', sa.Time(), nullable=False))
    op.drop_column('events', 'time')
    op.drop_column('events', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', sa.DATE(), nullable=False))
    op.add_column('events', sa.Column('time', mysql.TIME(), nullable=False))
    op.drop_column('events', 'end_time')
    op.drop_column('events', 'start_time')
    op.drop_column('events', 'end_date')
    op.drop_column('events', 'start_date')
    # ### end Alembic commands ###
