"""Add is_guest to attendance table

Revision ID: 480edf89b33b
Revises: 51a99a6db048
Create Date: 2025-01-24 22:44:51.751994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480edf89b33b'
down_revision: Union[str, None] = '51a99a6db048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('is_guest', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'is_guest')
    # ### end Alembic commands ###
