"""Create members table

Revision ID: b05dd43b61ad
Revises: 08a601f90a4a
Create Date: 2025-01-24 03:55:47.721019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05dd43b61ad'
down_revision: Union[str, None] = '08a601f90a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member_id', sa.String(length=60), nullable=False))
    op.create_foreign_key(None, 'users', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'member_id')
    # ### end Alembic commands ###
