"""Add group id to financial_records

Revision ID: df74f2701751
Revises: 3f2cfd419e9f
Create Date: 2025-01-24 13:25:10.813212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df74f2701751'
down_revision: Union[str, None] = '3f2cfd419e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('departments', sa.Column('description', sa.String(length=255), nullable=False))
    op.add_column('departments', sa.Column('head', sa.String(length=60), nullable=False))
    op.create_foreign_key(None, 'departments', 'members', ['head'], ['id'])
    op.add_column('financial_records', sa.Column('group_id', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'financial_records', 'groups', ['group_id'], ['id'])
    op.add_column('groups', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('groups', sa.Column('description', sa.String(length=255), nullable=False))
    op.add_column('groups', sa.Column('head', sa.String(length=60), nullable=False))
    op.create_foreign_key(None, 'groups', 'members', ['head'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'head')
    op.drop_column('groups', 'description')
    op.drop_column('groups', 'name')
    op.drop_constraint(None, 'financial_records', type_='foreignkey')
    op.drop_column('financial_records', 'group_id')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'head')
    op.drop_column('departments', 'description')
    op.drop_column('departments', 'name')
    # ### end Alembic commands ###
