"""Add association table for member, group, and department

Revision ID: e1e815d085cf
Revises: b05dd43b61ad
Create Date: 2025-01-24 05:19:45.403021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e815d085cf'
down_revision: Union[str, None] = 'b05dd43b61ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('member_id', sa.String(length=60), nullable=False))
    op.create_foreign_key(None, 'groups', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'member_id')
    # ### end Alembic commands ###
