"""Checks for status in Attendance table

Revision ID: efa19c52ac30
Revises: 3a065e8ef6c7
Create Date: 2025-01-24 16:12:43.210417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa19c52ac30'
down_revision: Union[str, None] = '3a065e8ef6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
