"""Create events table

Revision ID: fb3d3cfd1144
Revises: e1e815d085cf
Create Date: 2025-01-24 05:59:01.630021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3d3cfd1144'
down_revision: Union[str, None] = 'e1e815d085cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('events', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('events', sa.Column('time', sa.Time(), nullable=False))
    op.add_column('events', sa.Column('location', sa.String(length=255), nullable=False))
    op.add_column('events', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('events', sa.Column('category', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'category')
    op.drop_column('events', 'description')
    op.drop_column('events', 'location')
    op.drop_column('events', 'time')
    op.drop_column('events', 'date')
    op.drop_column('events', 'name')
    # ### end Alembic commands ###
